# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-08 23:03
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hookah', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='data',
            field=models.DateTimeField(default=datetime.datetime(2016, 2, 8, 23, 3, 41, 815223)),
        ),
        migrations.AlterField(
            model_name='order',
            name='place',
            field=models.CharField(choices=[('1', '\u0422\u0440\u043e\u0435\u0449\u0438\u043d\u0430'), ('2', '\u0414\u0430\u0440\u043d\u0438\u0446\u043a\u0438\u0439'), ('3', '\u041f\u0435\u0447\u0435\u0440\u0441\u043a\u0438\u0439')], max_length=5),
        ),
    ]
