# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-02-09 00:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hookah', '0002_auto_20160208_2303'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='data',
        ),
        migrations.RemoveField(
            model_name='order',
            name='place',
        ),
        migrations.AlterField(
            model_name='order',
            name='text',
            field=models.CharField(max_length=200),
        ),
    ]
